image: node:16
pipelines:
  default:
    - step:
        name: Build and Push push to nexus server
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm run publish
          - docker login http://project.pilgrimconsulting.group --username admin --password admin123
          - docker build -t admin/sentinel-fronend:latest .
          - docker push admin/sentinel-fronend:latest
        artifacts:
            - node_modules/**
        services:
          - docker
    # - step:
    #     name: Deploy to Kubernetes
    #     deployment: production
    #     script:
    #       - pipe: atlassian/google-gke-kubectl-run:1.3.1
    #         variables:
    #           KEY_FILE: $KUBE_CONFIG
    #           PROJECT: "wn-crs"
    #           COMPUTE_ZONE: "us-central1-c"
    #           CLUSTER_NAME: "cluster-1"
    #           KUBECTL_COMMAND: "apply"
    #           RESOURCE_PATH: "deployment.yml

