image: node:16
pipelines:
  default:
    - step:
        name: Build and Push push to nexus server
        caches:
          - node
        script:
        #   - npm install --legacy-peer-deps
        #   - npm run publish
          - docker login -u osmandiyaka -p nlabongbaba2015
          - docker build -t osmandiyaka/sentinel-fronend:latest .
          - docker push osmandiyaka/sentinel-fronend:latest
        artifacts:
            - node_modules/**
        services:
          - docker
    # - step:
    #     name: Deploy to  server
    #     deployment: production
    #     trigger: manual
    #     script:
    #      - echo "  [+] Start deploy script on the server"
    #      - ssh root@$DEPLOY_SERVER  "/docker/deploy.sh $BITBUCKET_COMMIT"


